### ISSUE TITLE
Sample for Warehouse

### ISSUE THREAD

**Issue by philippfrenzel** [yii2tech/balance#5]
Hi,

I would love to use the module for creating a minimized warehouse application.

What I would love to understand is:

1) Is each good an extra account or will this be stored within the transaction as an id?
2) What will be the counter account if I call the increase without a transfer account?
3) If i put the good id within the transaction can I recieve a balance by good by a predefined method?

Thanks in advance Philipp

**Comment by klimov-paul** [comment]
> 1) Is each good an extra account or will this be stored within the transaction as an id?

I am usnure I understand this question correctly.
You can save any data related to transaction, including information about goods in the form you like:
https://github.com/yii2tech/balance/blob/master/README.md#saving-extra-transaction-data-

> 2) What will be the counter account if I call the increase without a transfer account?

`transfer()` is a wrapper around 2 operations: `increase()` and `decrease()`. If you call only `increase()` you will increase amount at the affected account.
Usage of the `transfer()` is better for bookkeeping, since you can check the operations correction comparing sum of all account amount with zero.

> 3) If i put the good id within the transaction can I recieve a balance by good by a predefined method?

If you put `goodId` as a separated column in the `transaction` table, you can perform regular SQL query to find all related transactions.

**Comment by philippfrenzel** [comment]
Hi, thanks for the answers! I will try to implement it as a module which will be public and share it here;) So let's see if I got it correct ...:)
